language: cpp

matrix:
  include:
    - name: "osx gcc-7"
      os: osx
      osx_image: xcode10
      env: MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"

    - name: "linux gcc-7"
      os: linux
      addons:
        apt: { packages: [g++-7],
               sources:  [ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - name: "linux clang-6"
      os: linux
      addons:
        apt: { packages: [clang-6.0, libstdc++-7-dev],
               sources:  [llvm-toolchain-trusty-6.0, ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DVERBOSE_CONFIG=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - cat compile_commands.json
  - cmake --build . -- -j2
  - ctest -VV .

notifications:
  email: false
